// AI service powered by Google Gemini API
import { GoogleGenerativeAI } from '@google/generative-ai';
import { AIJobs } from './firestoreData';
import Toast from '../components/common/Toast';

// Initialize Gemini AI - ONLY for development
// NOTE: For production, API calls should go through your backend to keep API keys secure
let genAI = null;
let model = null;

// AI initialization is completely disabled in production builds
if (import.meta.env.DEV) {
  try {
    // This code is completely removed from production builds by Vite
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (apiKey && !apiKey.startsWith('your_')) {
      genAI = new GoogleGenerativeAI(apiKey);
      model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      console.log('🤖 Gemini AI initialized for development');
    } else {
      console.log('🚫 No valid Gemini API key found for development');
    }
  } catch (error) {
    console.warn('⚠️ Gemini AI initialization failed:', error.message);
  }
}

// Production builds will have null model, ensuring AI features show fallback content
if (!import.meta.env.DEV) {
  console.log('🔒 AI features disabled in production for security. Use backend API instead.');
}

const parseJsonFromResponse = (text) => {
  try {
    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    return JSON.parse(cleaned);
  } catch (e) {
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      try {
        return JSON.parse(jsonMatch[0]);
      } catch (e2) {
        return null;
      }
    }
    return null;
  }
};

export const AIService = {
  async summarize({ noteId, inputText, createdBy }) {
    const jobId = await AIJobs.create({ type: 'summary', noteId, inputText: inputText?.substring(0, 500), status: 'processing', createdBy });
    
    try {
      let output;
      if (model && inputText) {
        const prompt = `Analyze this text and provide a summary in JSON format:
{
  "bullets": ["point 1", "point 2", "point 3"],
  "tldr": "one sentence summary",
  "keyTerms": ["term1", "term2", "term3"]
}

Text: ${inputText}

Provide 3-5 bullet points, a TL;DR, and key terms. Return ONLY valid JSON.`;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        output = parseJsonFromResponse(text) || {
          bullets: ['Summary generated', 'Key points extracted', 'Analysis complete'],
          tldr: 'AI-powered summary of the content',
          keyTerms: ['Analysis', 'Summary', 'Key Points']
        };
      } else {
        output = {
          bullets: ['AI features are disabled in production', 'Configure backend API for AI summaries', 'Using demo content for now'],
          tldr: 'AI features coming soon - backend integration required',
          keyTerms: ['Demo', 'Backend', 'Coming Soon']
        };
      }
      
      await AIJobs.update(jobId, { status: 'completed', output });
      Toast.success('AI summary generated');
      return { jobId, output };
    } catch (error) {
      console.error('Summarization error:', error);
      await AIJobs.update(jobId, { status: 'error', error: error.message });
      Toast.error('Summary generation failed');
      return { jobId, output: null };
    }
  },

  async generateMCQ({ inputText, count = 10, createdBy }) {
    const jobId = await AIJobs.create({ type: 'mcq', inputText: inputText?.substring(0, 500), status: 'processing', createdBy });
    
    try {
      let output;
      if (model && inputText) {
        const prompt = `Generate ${count} MCQs from this text in JSON format:
[
  {
    "id": 1,
    "question": "Question text?",
    "choices": ["A", "B", "C", "D"],
    "correctIndex": 0,
    "explanation": "Why this is correct"
  }
]

Text: ${inputText}

Generate exactly ${count} questions. Return ONLY valid JSON array.`;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        output = parseJsonFromResponse(text);
        
        if (!Array.isArray(output)) {
          output = Array.from({ length: count }, (_, i) => ({
            id: i + 1,
            question: `Question ${i + 1} generated by AI`,
            choices: ['Option A', 'Option B', 'Option C', 'Option D'],
            correctIndex: 0,
            explanation: 'AI-generated question'
          }));
        }
      } else {
        output = Array.from({ length: count }, (_, i) => ({
          id: i + 1,
          question: `Demo Question ${i + 1} - AI features coming soon!`,
          choices: ['Coming Soon', 'Backend Required', 'Demo Option', 'AI Integration Needed'],
          correctIndex: 0,
          explanation: 'This is a demo question. AI features are disabled in production for security.'
        }));
      }
      
      await AIJobs.update(jobId, { status: 'completed', output });
      Toast.success('MCQs generated');
      return { jobId, output };
    } catch (error) {
      console.error('MCQ generation error:', error);
      await AIJobs.update(jobId, { status: 'error', error: error.message });
      Toast.error('MCQ generation failed');
      return { jobId, output: [] };
    }
  },

  async flashcards({ inputText, count = 20, createdBy }) {
    const jobId = await AIJobs.create({ type: 'flashcard', inputText: inputText?.substring(0, 500), status: 'processing', createdBy });
    
    try {
      let output;
      if (model && inputText) {
        const prompt = `Create ${count} flashcards from this text in JSON format:
[
  {
    "front": "Question or term",
    "back": "Answer or definition"
  }
]

Text: ${inputText}

Generate exactly ${count} flashcards. Return ONLY valid JSON array.`;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        output = parseJsonFromResponse(text);
        
        if (!Array.isArray(output)) {
          output = Array.from({ length: count }, (_, i) => ({
            front: `Term ${i + 1}`,
            back: `AI-generated definition ${i + 1}`
          }));
        }
      } else {
        output = Array.from({ length: count }, (_, i) => ({
          front: `Demo Term ${i + 1}`,
          back: `AI flashcards coming soon! Backend integration required for security.`
        }));
      }
      
      await AIJobs.update(jobId, { status: 'completed', output });
      Toast.success('Flashcards created');
      return { jobId, output };
    } catch (error) {
      console.error('Flashcard generation error:', error);
      await AIJobs.update(jobId, { status: 'error', error: error.message });
      Toast.error('Flashcard generation failed');
      return { jobId, output: [] };
    }
  },

  // Enhanced internship matching with Gemini insights
  async matchInternships({ userSkills = [], internships = [] }) {
    try {
      if (model && userSkills.length > 0 && internships.length > 0) {
        const prompt = `Given user skills: ${userSkills.join(', ')}

Score these internships (0-100) in JSON format:
${internships.map((i, idx) => 
  `${idx}. ${i.role} at ${i.company} - Skills: ${(i.skills || []).join(', ')}`
).join('\n')}

Return JSON: [{"index": 0, "score": 85, "reason": "why"}]`;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        const matches = parseJsonFromResponse(text);
        
        if (Array.isArray(matches)) {
          return internships.map((internship, idx) => {
            const match = matches.find(m => m.index === idx) || {};
            return {
              ...internship,
              matchScore: match.score || 0,
              matchReason: match.reason || 'Based on skills',
              aiEnhanced: true
            };
          }).sort((a, b) => b.matchScore - a.matchScore);
        }
      }
      
      // Fallback to simple matching
      const set = new Set(userSkills.map(s => s.toLowerCase()));
      return internships.map(i => ({
        ...i,
        matchScore: (i.skills || []).reduce((acc, s) => 
          acc + (set.has(String(s).toLowerCase()) ? 20 : 0), 0
        ),
        aiEnhanced: false
      })).sort((a, b) => b.matchScore - a.matchScore);
    } catch (error) {
      console.error('Matching error:', error);
      const set = new Set(userSkills.map(s => s.toLowerCase()));
      return internships.map(i => ({
        ...i,
        matchScore: (i.skills || []).reduce((acc, s) => 
          acc + (set.has(String(s).toLowerCase()) ? 20 : 0), 0
        ),
        aiEnhanced: false
      })).sort((a, b) => b.matchScore - a.matchScore);
    }
  },

  isConfigured() {
    return !!model;
  },

  getModelInfo() {
    return { 
      configured: !!model, 
      model: model ? 'gemini-1.5-flash' : 'Not configured',
      provider: 'Google Gemini API'
    };
  }
};

